### ISSUE TITLE
Remove unnecessary dependencies

### ISSUE THREAD

**Issue by KizzyCode** [wireapp/proteus#17]
There are 2 in my opinion unnecessary dependencies in proteus.

The first one is the `libc`-crate which is only used to get the `c_int`-type. However this is completely unnecessary because the `c_int`-type is also defined in the `std`-crate: `std::os::raw::c_int`.
If you'd replace this dependency in "internal/ffi.rs" you could omit the entire `libc`-crate.
(I've done this; it also passes all tests on macOS.)

The second one is the byteorder-crate which is also used to serialize _one_ `u32` as big-endian.

And thank you very much that you make your software open-source under the GPL 😄

**Comment by raphaelrobert** [comment]
I guess you are right about both things. We can fix that in the next iteration, unless you want to submit a fix yourself.

**Comment by neongreen** [comment]
I'll make a fix.

**Comment by neongreen** [comment]
See https://github.com/wireapp/proteus/pull/18
