### ISSUE TITLE
compiled failed with sodiumoxide 0.1.0

### ISSUE THREAD

**Issue by zhaohansprt** [wireapp/proteus#19]
error[E0308]: mismatched types
  --> /root/.cargo/git/checkouts/proteus-c72aed2360065c51/cda560b/src/lib.rs:28:5
   |
27 | pub fn init() -> bool {
   |                  ---- expected `bool` because of return type
28 |     sodiumoxide::init()
   |     ^^^^^^^^^^^^^^^^^^^ expected bool, found enum `std::result::Result`
   |
   = note: expected type `bool`
              found type `std::result::Result<(), ()>`

**Comment by neongreen** [comment]
Fixed.

**Comment by neongreen** [comment]
(Now we use sodiumoxide-0.1, and 0.0.16 becomes unsupported)
